'use client';

import { useState } from "react";
import { BackHeader } from "@/components/BackHeader";

const FAQItem = ({ question, answer }: { question: string; answer: string }) => {
    const [isOpen, setIsOpen] = useState(false);
    return (
        <div className="border-b border-gray-100 last:border-0">
            <button
                className="flex w-full items-center justify-between py-4 text-left group"
                onClick={() => setIsOpen(!isOpen)}
            >
                <span className={`font-medium text-gray-900 group-hover:text-[#005461] transition-colors ${isOpen ? 'text-[#005461]' : ''}`}>
                    {question}
                </span>
                <span className={`transform transition-transform duration-200 text-gray-400 ${isOpen ? 'rotate-180 text-[#005461]' : ''}`}>
                    ▼
                </span>
            </button>
            <div
                className={`overflow-hidden transition-all duration-300 ease-in-out ${isOpen ? 'max-h-48 opacity-100 mb-4' : 'max-h-0 opacity-0'}`}
            >
                <p className="text-sm text-gray-600 leading-relaxed bg-gray-50 p-3 rounded-xl">
                    {answer}
                </p>
            </div>
        </div>
    );
};

export default function FAQPage() {
    return (
        <div className="min-h-screen bg-white pb-20">
            <BackHeader title="FAQ" className="py-4 px-0" />

            <div className="px-4">
                <div className="text-center py-6 mb-2">
                    <h2 className="text-2xl font-bold text-gray-900 mb-2">How can we help?</h2>
                    <p className="text-gray-500">Common questions about QuickFix</p>
                </div>

                <div className="space-y-8">
                    <section>
                        <h3 className="text-sm font-bold text-[#005461] uppercase tracking-wider mb-4 px-2">For Customers</h3>
                        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 px-5 py-2">
                            <FAQItem
                                question="How do I book a service?"
                                answer="Simply browse for the service you need, select a provider based on reviews and ratings, and click 'Book Inspection'. You'll pay a fixed visiting charge of ₹99 to confirm the booking."
                            />
                            <FAQItem
                                question="What is the Job Verification Code?"
                                answer="For your safety, we use a two-step verification process. You'll receive a Start Code to give the provider when they arrive, and a Completion Code to give them when the work is finished to your satisfaction."
                            />
                            <FAQItem
                                question="How do I pay?"
                                answer="The visiting charge is paid online to confirm the booking. The final bill for the service (labor + materials) is generated by the provider after the job is done, and you can pay it securely through the app."
                            />
                        </div>
                    </section>

                    <section>
                        <h3 className="text-sm font-bold text-[#005461] uppercase tracking-wider mb-4 px-2">For Providers</h3>
                        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 px-5 py-2">
                            <FAQItem
                                question="How do I get paid?"
                                answer="Your earnings are tracked in the app. Payments from customers are processed securely and transferred to your registered bank account on a weekly basis."
                            />
                            <FAQItem
                                question="Can I reject a booking?"
                                answer="Yes, you can accept or decline booking requests based on your availability. However, frequent cancellations may affect your rating and visibility on the platform."
                            />
                        </div>
                    </section>
                </div>
            </div>
        </div>
    );
}
